name: Test
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8.15.3
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Run test
        run: pnpm test
